name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v6
        with:
          node-version: "22.x"
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Test
        run: pnpm run test
        env:
          TEST_BOARD_ID: ${{secrets.TEST_BOARD_ID}}
